# Generated by Django 4.2.7 on 2023-11-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kanban", "0002_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tag",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="work_time",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
